### ISSUE TITLE
Make API dataset

### ISSUE THREAD

**Issue by ThunderCow** [ThunderCow/OHAMA-PIOS#21]

**Comment by seawaterz** [comment]
<h3>To make an API data-set, below is the procedure to do this task:</h3>
1. We need to write python script code through JSON file.
2, As we are using OpenMCT, we will fetch this file into OpenMCT.
3. Run this API data in order to collect sensors data and display it.

**Comment by seawaterz** [comment]
Since we have decided to drop using OpenMCT where we needed to make custom API data-set to send over to OpenMCT for displaying a graphical result. Therefore, the team is not working on it anymore and closing the issue for the moment.
