### ISSUE TITLE
Unable to install libraries to run programming files

### ISSUE THREAD

**Issue by seawaterz** [ThunderCow/OHAMA-PIOS#23]

**Comment by seawaterz** [comment]
As we progressed further towards the project, there we needed to install some additional libraries (such as installing matplotlib and pandas). The problem is still there as the team has tried different ways to install them but got errors at the end and terminate the installation.
However, the team is still struggling to fix these problems in order to run the project effectively.

**Comment by ThunderCow** [comment]
We have found plotly and dash to work for what we currently want for this project. So we have not tried to install matplotlib and pandas anymore.
